import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // OptinMockup theme classes (dynamic from optin-themes.ts)
    "bg-white",
    "bg-white/[0.02]",
    "bg-white/[0.03]",
    "bg-white/[0.04]",
    "bg-white/10",
    "bg-white/20",
    "border-white/[0.06]",
    "border-white/[0.08]",
    "border-white/10",
    "border-white/20",
    "border-white/30",
    "border-white/40",
    "text-gray-800",
    "text-[#a1a1aa]",
    "text-[#fafafa]",
    "text-[#71717a]",
    "text-[#52525b]",
    "bg-[rgba(251,191,36,0.25)]",
    "bg-[rgba(251,191,36,0.15)]",
    "text-[#fbbf24]",
    "bg-[#7c3aed]",
    "bg-transparent",
    "focus:border-[#7c3aed]/60",
    "focus:ring-2",
    "focus:ring-[#7c3aed]/20",
    "focus:border-[#fbbf24]/50",
    "focus:ring-[#fbbf24]/20",
    "text-gray-600",
    "bg-gray-100",
    "bg-gray-50",
    "bg-gray-800/60",
    "border",
    "border-gray-200",
    "border-0",
    "shadow-[0_4px_24px_rgba(0,0,0,0.15)]",
    "shadow-[0_8px_32px_rgba(0,0,0,0.3)]",
    "shadow-none",
    "shadow-xl",
    "hover:brightness-110",
    "hover:bg-white/[0.06]",
    "hover:border-white/60",
    "bg-amber-100",
    "bg-amber-500/20",
    "text-red-400",
    "text-red-400/80",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // MORFEUS Official Palette v1.0
        night: "#0B0B0C",
        midnight: "#201F6E",
        persian: "#392CB8",
        majorelle: "#533DFC",
        neon: "#6475FA",
        vista: "#8CA5F7",
        "ghost-white": "#E4E7F0",
        forge: "#E8650A",
        // Legacy/Generic mapping (mapping majorelle to purple for backward compat if needed)
        purple: {
          DEFAULT: "#533DFC", // Majorelle Blue
          50: "#EFEDFB",
          100: "#DDD9F8",
          200: "#BBB4F1",
          300: "#998FEA",
          400: "#7764E3",
          500: "#533DFC",
          600: "#533DEC",
          700: "#3925C7",
          800: "#2B1C96",
          900: "#1D1365",
          950: "#130D43",
        },
      },
      fontFamily: {
        outfit: ["var(--font-outfit)", "sans-serif"],
        "dm-sans": ["var(--font-dm-sans)", "sans-serif"],
        prodigy: ["var(--font-prodigy)", "sans-serif"],
      },
      transitionDuration: {
        "1000": "1000ms",
      },
      borderWidth: {
        "1.5": "1.5px",
      },
    },
  },
  plugins: [],
};
export default config;
